# Generated by Django 3.0.7 on 2020-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('publishedAt', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('urlToImage', models.FileField(upload_to='')),
            ],
        ),
    ]
